# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = example
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../../OpenCV-4.5.0/build/x64/vc15/lib" \
    -lopencv_world450d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
